/** Declaration file generated by dts-gen */

export default class pomelo{
	public static disconnect(func?);
	public static init(arg1,arg2);
	public static request(route,msg,callback);
	public static on(event,callback);
	public static notify(route,msg);
	public static reconnect();
	public static emit(eventName)
}

